# Generated by Django 5.1 on 2024-08-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publish_date',
            new_name='pub_date',
        ),
    ]
